# Generated by Django 3.0.3 on 2020-08-19 13:16

import core.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ShortenedURL',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expanded_url', models.TextField(validators=[django.core.validators.URLValidator])),
                ('shortened_url', models.CharField(default=core.models.default_shortened_url, max_length=20, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
